#单一窗口登录密码（只支持卡登录）
single_widow:
    # 操作员卡密码
    password: 88888888

#rabbitmq配置(请设置交换机为 直连交换机（Direct Exchange））
rabbitmq:
    user: 'admin'
    password: 'admin'
    host: '192.168.2.80'
    port: 5672
    exchange: 'hgBill.autoGetTax.topic.exchange'
    queue: 'hgBill.autoGetTax'
    routing_key: 'hgBill.autoGetTax'

#税费文件上传接口配置
upload_api:
    # 税单、货单二进制文件流数据上传接口
    tax_goods_api: 'https://xht.sunron.net/api/import/operationCustomsBillReportInfo/declare/uploadBillMultipart/'

    # 税费json对象上传接口：
    tax_json_api: 'https://xht.sunron.net/api/import/operationCustomsBillReportInfo/declare/uploadTaxJson'

    #mq接口访问地址
    rabbitmq: 'http://192.168.2.80:15672/api/queues/%2F/hgBill.autoGetTax'

# 抓取模式
grab_mode:
    # 抓取模式: 1:税单和货单都抓取； 2：只抓取税单； 3：只抓取货单
    mode: 2

#本地文件配置
localfile:
    #file_path_prefix 需要与 save_path路径设置为相同路径
    file_path_prefix: 'C:\taxefile\'
    save_path: 'C:/taxefile/'
    uploaded_path: 'C:/uploadedtax/'
    uploadfail_path: 'C:/uploadfailtax/'
    #chromedebugwindow: 'C:/dist/run/chromedebugwindow.bat'
    chromedebugwindow: 'C:/Users/admin/Desktop/chromedebugwindow.bat'

#邮箱配置
email:
    #收件人邮箱,如有多个，请用英文逗号分隔；示例：['xxx@xx.com','xxx@xx.com','xxx@xx.com']
    receiver: ['2224599145@qq.com']